### ISSUE TITLE
Velo upload_file() broken?

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-OUI/acme-web-fe#119]
Im not sure if Im just doing it wrong, but I cant get the VeloAPIs upload_file method to work. I know this worked at some point, because I was able to upload a test file, but now all I get are errors. 

I made a test file named 'uploadtest.txt' and then ran the following commands.

```
import VeloAPI
v = VeloAPI.Velo()
v.start_jvm()
r = v.init_velo(<username>,<password>)
v.upload_file('/Users/baldwin32/projects/acme-web-fe/apps/velo', 'uploadtest.txt')
```

and get the output

```
1 None
2 (<class 'jpype._jexception.java.lang.RuntimeExceptionPyRaisable'>,    RuntimeExceptionPyRaisable(<jpype._jclass.java.lang.RuntimeException object at 0x1010c4e50>,),  <traceback object at 0x10ecaa5a8>)
3 <class 'jpype._jexception.java.lang.RuntimeExceptionPyRaisable'>
4 java.lang.RuntimeException: Error sending content.
5 73
  File "VeloAPI.py", line 73, in upload_file
    resMgr.bulkUpload(fileServerMap, None)
6 None
```

**Comment by bibiraju** [comment]
I just tried it from my end, it's working fine. Can you make sure the paths are correct. Also can you please try again, to make sure that it's not network error.

**Comment by sterlingbaldwin** [comment]
This might have been a lab network issue. Thanks for checking, it looks like its working now, I have no idea why it was failing yesterday.
