### ISSUE TITLE
Velo delete file/folder

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-OUI/acme-web-fe#123]
I noticed that over the last week a ton of new fake_acme_test_cases popped up in the test user folder for velo, which reminded me that we currently have no way of removing files or folders. It would be nice to have delete_file(file_path) and delete_folder(folder_path) methods in the VeloAPI. Not critical, but we're going to want this at some point.

**Comment by bibiraju** [comment]
Added methods in VeloAPI to delete resources from Velo

**Comment by sterlingbaldwin** [comment]
Thanks!
