### ISSUE TITLE
Velo create folder should fail if folder exists

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-OUI/acme-web-fe#125]
Currently, if velo.create_folder() is called with the name of a folder that already exists, it exists normally as though it created the folder. This should be changed so an error is thrown so the user can be alerted that the folder was not created.

**Comment by mattben** [comment]
@bibiraju Can you take a look at this

**Comment by bibiraju** [comment]
I will work on this and make required changes to the Velo Python API
