### ISSUE TITLE
acme velo to cdatwe

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#136]
since velo holds the data, please implement a method that the front end can call with a username and .nc  (open dap) url and make a call to the cdatweb visualization server and return the .png file. @sterlingbaldwin @jbeezley @chaosphere2112 can help explain the requirements

**Comment by sterlingbaldwin** [comment]
To get this to work, we're going to have to figure out how the velo/esgf/cdatweb servers are mounting the shared storage in CADES.

Also, this means that the project is going to stop being portable, and will start to only be able to be run from the production server, unless we want to setup the devel server to have the same mount point so all the paths work out.
