### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#141]
Sterling please fix your pep3 issues and make the build pass. Also fix the and merge the pull request

**Comment by sterlingbaldwin** [comment]
Well my issues are fixed, but with Sam's pull request we are now running the selenium tests with each build, which are now the issue. A lot has changed since the selenium tests were written, so I'll go in and see what I can do about getting them up to snuff.

**Comment by mattben** [comment]
:+1:
