### ISSUE TITLE
CDATWeb plot

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#157]
I've updated dashboard.js with a working open dap url, and its variable (from the cdatweb example). Once logged in, from the dashboard. clicking CDAT in the left menu should bring the plot back, and is failing somewhere in cdat.js. Can you debug it from http://acme-devel.llnl.gov/acme/dashboard. It may need an updated cdat.js

**Comment by jbeezley** [comment]
Your `cdat.js` is out of date.  You probably just need to update to the version here: https://github.com/UV-CDAT/cdatweb/blob/master/static/cdatweb/vtk_view/js/cdat.js

**Comment by mattben** [comment]
Thank you Jon.
