### ISSUE TITLE
User can download a zip of diagnostic output files

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-OUI/acme-web-fe#172]
As a user, once a diagnostic run has finished, I should be able to download a zip file containing the complete output, including the console output, climo files, png and svg images.

**Comment by sterlingbaldwin** [comment]
This is now working for diagnostic output. For the time being, the server is zipping the output directory every time a user makes a request, which is sub optimal as it takes ~30 seconds to perform the zip. Additionally its just leaving the zip sitting in the project root directory, so tomorrow Im going to have it save it to the output directory and check before zipping.

**Comment by sterlingbaldwin** [comment]
Done and done.

**Comment by chaosphere2112** [comment]
👍 I've just submitted the PR to automatically upload the files to Diagnostics Viewer as part of the metadiags run (UV-CDAT/uvcmetrics#224), should get merged on Monday. Also, the logging update has been pushed onto aims4, should you choose to play with it.

**Comment by sterlingbaldwin** [comment]
(y)
