### ISSUE TITLE
Diagnostic viewer integration

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-OUI/acme-web-fe#176]
After a diagnostic run completes, its output should automatically be uploaded to the diagnostic viewer, and a link created so the user can go to it. For this to work we need to get a couple things working.

1) The user should be able to create a diag view account through the dashboard. We want to cut down on them having to bounce around between sites, and creating multiple accounts is cumbersome. Once the account is created, the dashboard can store their key, removing the need to log in each time.

2) When the diagnostic run finishes, and the output is uploaded, the UI needs to add a link to take the user to the diag viewers page. Either the upload function should return a URL, or I if I know the format of the URLs I can just render the link from a template given the username and dataset.  

Thoughts Sam?

**Comment by chaosphere2112** [comment]
![supervisor](https://cloud.githubusercontent.com/assets/718512/17870470/876fe520-686c-11e6-9459-428bef704383.gif)

**Comment by chaosphere2112** [comment]
1) Account registration... ugh. Yeah, we need a shared key that will allow you to bypass the recaptcha, but other than that, it should be fine.
2) There's no direct linking to a dataset right now, but I have that on my list of features to add. I'll just give you the format and never change it :+1: 

Do you still want the API endpoint for fetching the list of datasets for a user?

**Comment by sterlingbaldwin** [comment]
I dont think I need to be able to pull the list of a users datasets, since Im just going to be uploading everything they run through metadiags. 

As long as theres some common format for linking to the dataset pages thats fine.
