### ISSUE TITLE
save layout

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#24]
on the production server when you click save layout it reloads the page and does not save the layout. I do not think this is a code issues but rather a configuration issues. Possible the db file is not writable.

**Comment by sterlingbaldwin** [comment]
I cant do anything with this since I dont have access to the production server. Also, when I go to it I get a completely blank page, so for the time being I cant reproduce the problem.

**Comment by mattben** [comment]
CNR
