### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#38]
Review ACME Overarching UI code, test locally.
Update README.md from your install experience.

Code: https://github.com/ACME-OUI/acme-web-fe

**Comment by mattben** [comment]
@jfharney are you ready to close this?

**Comment by jfharney** [comment]
@mattben  I would like to leave this open.  I haven't explored the entire code base as of yet.

**Comment by mattben** [comment]
:+1: Sounds Good, Thanks for your commitment

**Comment by mattben** [comment]
@jfharney how goes it?

**Comment by mattben** [comment]
Since this is not really an issues i'm closing it to thus close it in JIRA. @jfharney if you need any help or have any questions, email me.
