### ISSUE TITLE
Issues Features

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#39]
Add ESGF, CDATWEB, Dashboard to Issue tracker

UV-CDAT looks good

**Comment by chaosphere2112** [comment]
@mattben So, my original idea was to implement an email-based subscription that was separate from the standard Django authentication scheme, but I'm thinking that's way too much work. I'm thinking I can switch over to the standard Django way for now and this can just be one more value-add for people to use the app.

**Comment by chaosphere2112** [comment]
FYI, [here's an issue made using the devel instance](https://github.com/UV-CDAT/uvcdat-site/issues/74)

**Comment by mattben** [comment]
@chaosphere2112 :+1:Your the man

**Comment by mattben** [comment]
@chaosphere2112 looks like we need to add acme-web-fe as a project and i'll need to be able to set up our sprints with it. like you said eat our own dog food. I need to be able to add labels, milestone, and assignee and having tab complete for possible github options would be A+ work.

**Comment by chaosphere2112** [comment]
Will do; I'll get this done by Tuesday.
