### ISSUE TITLE
Velo Configuration 

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#40]
- Configure Velo to work in devel and prod.
- Finish file Saving
- use update VELO api to add file retrieving to dashboard 

Prod Server: http://acme-web-fe.ornl.gov/acme/
Devel Server: http://acme-devel.llnl.gov/acme/

**Comment by sterlingbaldwin** [comment]
All Velo calls are now being stored in their own scripts in the apps/velo folder, and are being called from django via a subprocess. This fixed the issue of not being able to start the jvm after stopping it, and having the jvm core dump all over itself. Velo can now be accessed through the dashboard, and I have it setup to display a file tree with the users home folder, and when they click on a file have it pulled from Velo, stored in the server, and sent back to the user where they can edit it. Right now Im working on saving the file after changes have been made. What I really need to do is make a velo-toolbar, exposing all the functionality through some nice buttons.
