### ISSUE TITLE
Adding Service to VELO API

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#41]
Add fetch to the python api. Currently we are able to save files remotely.
looking at alfresco we can see the files have in fact been saved.
We now need a 3 service call:
1. User Models
   - Takes in a user name
   - Returns a list of directories in users home directory 
2. Directory Content
   - Takes in a path (~/user/foldername)
   - returns a list of content
3. File Content
   - Takes in a path(~/user/foldername/config.py) 
   - returns the content of the file

**Comment by mattben** [comment]
@bibiraju I believe this is done? Can you close it if so.

**Comment by bibiraju** [comment]
Added new functionality to VeloAPI as requested.
