### ISSUE TITLE
Velo server is down

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-OUI/acme-web-fe#69]
The server running at http://acmetest.ornl.gov/ is returning the default Apache page, and the velo API is returning status 500s on all requests. This is the 3rd or 4th time this has happened, how can we change the server to ensure it says operational?

**Comment by mattben** [comment]
I think we just need to ask @bibiraju to re start it. I bet ORNL did a restart or unplugged or something silly. Not the first or last time this will happen to all of us.

**Comment by mattben** [comment]
@sterlingbaldwin why or how was this issues closed?

**Comment by sterlingbaldwin** [comment]
@mattben I think the issue was that the lab was blocking my requests, not that the velo server was down. I noticed when I came back later to try again (after I had opened my ports to make a commit) it was working again.
