### ISSUE TITLE
Testing Dashboard

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#76]
using [robot](http://robotframework.org) write a [Selenium](http://www.seleniumhq.org) test:
- Dashboard loading normally (no saved default)
- Dashboard loading normally (from saved default)

using [PyUnit](http://pyunit.sourceforge.net) write a unit test for:
- Grid view [function](https://github.com/ACME-OUI/acme-web-fe/blob/master/apps/web_fe/views.py#L233)

**Comment by sterlingbaldwin** [comment]
Im going to see if I can save and load layouts via robot too. Once this testing sprint is over I need to add functionality to delete layouts.

**Comment by sterlingbaldwin** [comment]
I wont be able to test without a layout until Ive put in the functionality to remove layouts, since the only users that have no default layout are new users that havent made a layout, so once the test user makes their first default, it cant test the loading without a default anymore.
