### ISSUE TITLE
Robot Documentation 

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#77]
Please create a wiki page on how to create a basic robot/selenium﻿ test.

**Comment by sterlingbaldwin** [comment]
A basic write up for using robot to test the front end. Im still trying to figure out how to test the back end python with it.

https://github.com/ACME-OUI/acme-web-fe/wiki/Writing-front-end-tests-with-the-RobotFramework-and-Selenium

**Comment by sterlingbaldwin** [comment]
Im going to leave this open so I remember to keep posting notes as I learn more about robot.

**Comment by sterlingbaldwin** [comment]
Ive updated the wiki article a couple times, and now I think its in a good place for the time being.
