### ISSUE TITLE
Issues alpha testing

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#82]
http://acme-devel.llnl.gov/acme/
- Create account
- Create issues http://acme-devel.llnl.gov/issues/

**Comment by mccoy20** [comment]
No problem creating account and logging in! Interface looking good, easy to follow and read. The captcha was not too obvious, but ultimately the first try was correct, so it was readable.

**Comment by mccoy20** [comment]
I get "403 Forbidden" when I go to http://acme-devel.llnl.gov/issues/ "Submit issue"

**Comment by mattben** [comment]
Sorry, I'll update the Devel server in the morning

**Comment by mccoy20** [comment]
I am still getting 403 error.

**Comment by chaosphere2112** [comment]
@mccoy20 I'll tag you in the pull request that fixes this issue.

**Comment by chaosphere2112** [comment]
@mccoy20 This issue should be resolved, though you'll have to make a new user account.

**Comment by mccoy20** [comment]
I created a new account and was able to create issues. I am not sure where to find them now though.

**Comment by chaosphere2112** [comment]
Hm... email must be broken on the server. I'll get that sorted out and let you know when you should try again.

**Comment by chaosphere2112** [comment]
Working with Tony to figure out what SMTP server to use; the lab's SMTP server is behind the firewall.

**Comment by mattben** [comment]
@chaosphere2112 @mccoy20 @williams13 is this a Dead feature replaced by request bot? If so I'll close it. If not I'll close it and reopen a new corrected issues for feature enhancements.

**Comment by chaosphere2112** [comment]
*Request Hub

**Comment by mattben** [comment]
Yea that, this is the correct linked issues #39

**Comment by mattben** [comment]
see Request Hub
