### ISSUE TITLE
Testing Devel Setup

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#83]
please set up the project locally following the README and report any issues you have getting the site up and running locally.
- README.md
  - https://github.com/ACME-OUI/acme-web-fe/blob/master/README.md
- Repo
  - https://github.com/ACME-OUI/acme-web-fe
- Issues
  - https://github.com/ACME-OUI/acme-web-fe/issues
- Wiki
  - https://github.com/ACME-OUI/acme-web-fe/wiki
- Devel
  - http://acme-devel.llnl.gov/acme/
- Prod
  - http://acme-web-fe.ornl.gov/acme/

**Comment by mattben** [comment]
@bibiraju how goes it?

**Comment by bibiraju** [comment]
I followed the instructions and set it up on my Windows machine. Not sure how to test on Windows

**Comment by mattben** [comment]
what IDE are you using?

**Comment by mattben** [comment]
None of know windows well enough, and since your able to create new features to the VELO api with out issues. Then this is real a non issues. We can work on this at a later time if you'd still like to make the dashboard run locally.
