### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#86]
Once I create a user, I am not logged in automatically and have to go back to the log in page. Once new user creation is completed the user should be log in.

**Comment by sterlingbaldwin** [comment]
This used to be working....

**Comment by mattben** [comment]
`used` being the operative word

**Comment by sterlingbaldwin** [comment]
Fixed in my next pull request.

**Comment by chaosphere2112** [comment]
@sterlingbaldwin Probably shouldn't close issues till you actually resolve them :wink:

**Comment by sterlingbaldwin** [comment]
Ok, well review my PR and lets get this into master. :tractor:
