### ISSUE TITLE
VeloAPI Path

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#87]
Velo API path is hardcoded in /apps/velo/VeloAPI.py. this should be a variable imported from the local_settings file. Its a pain to remember to update that file every time we update prod and devel.

**Comment by sterlingbaldwin** [comment]
I didnt want to have to make people add the path in local_settings if they didnt have to, so I just use os.getcwd() to figure out what the path is. Its a tiny little bit of computational overhead, but its so small that I dont think it really matters. If anyone has a problem with this we can put it in local_settings, I just figured the cost was so low, and I didnt want to add more steps for setting up the project.
