### ISSUE TITLE
CDATWEB Integration 

### ISSUE THREAD

**Issue by mattben** [ACME-OUI/acme-web-fe#89]
Please work with @sterlingbaldwin to write a javascript class for calling a vis server.
- in local_settings.py there should be `VIS_SERVER = "http://acme-uvcdat.ornl.gov/vis/path"`
- game plan how the windows should flow for the dashboard
  - when a user is looking at the output files clicking one should open the file in a new cdatweb interactive window
  - when a user searches ESGF and clicks a opendaped variable it should open in a new cdatweb interactive window
  - once the classic viewer is implemented a user can look at a generated png file then open it in a new cdatweb interactive window
  - other use cases...

**Comment by jbeezley** [comment]
Sounds like a plan.  One thing to remember going forward is that all calls related to interacting with the vis server will be asynchronous.  You will probably have to assume an interface with promises, à la

``` javascript
doSomething(...).then(function (...) {}).then(function (...) {}).else(function (...) {});
```

**Comment by sterlingbaldwin** [comment]
Jon, when you have time it would be great to schedule a 'sit down' to talk this through.

**Comment by chaosphere2112** [comment]
Oh, dial me in on that; I'd like to get a look at what you've got going.

**Comment by jbeezley** [comment]
My availability is somewhat limited for the next few weeks.  I can meet Friday afternoon.  I'm not sure what my schedule will be next week yet, but I should be able to carve out some time.  After that, I'm on vacation for a while.

**Comment by sterlingbaldwin** [comment]
Friday would be perfect for me. Let me know whatever time works for you.
